[project]
name = "ai-agents"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "langchain==1.0.7",
    "langchain-mcp-adapters==0.1.13",
    "langchain-openai==1.0.3",
    "langchain-text-splitters>=1.0.0",
    "pypdf>=6.2.0",
    "unstructured==0.18.20",
    "markdown>=3.10",
    "langchain-community>=0.4.1",
    "langchain-chroma>=1.0.0",
    "langgraph==1.0.3",
    "langgraph-api==0.5.14",
    "langgraph-cli[inmem]>=0.4.7",
    "psycopg2-binary>=2.9.11",
    "pytest>=9.0.1",
    "agentevals>=0.0.9",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
